name = "SYKRE"
uuid = "6a251b59-01d6-43da-b447-db219cb26ab4"
authors = ["Valerie Bettaque <v.l.bettaque@gmail.com>"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
BlockArrays = "8e7c35d0-a365-5155-bbbb-fb81a777f24e"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
Integrals = "de52edbc-65ea-441a-8357-d3a637375a31"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
SkewLinearAlgebra = "5c889d49-8c60-4500-9d10-5d3a22e2f4b9"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
BenchmarkTools = "1.6.0"
BlockArrays = "1.7.0"
Combinatorics = "1.0.3"
Distributions = "0.25.120"
Plots = "1.40.14"
ProgressMeter = "1.11.0"
SkewLinearAlgebra = "1.0.0"
StaticArrays = "1.9.14"
